version: 1.0.1.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore

build:
  publish_nuget: true
  project: Utilities.sln

after_test:

artifacts:
  - path: Utilities\bin\Release\Emerlahn.Utilities.dll
    name: Emerlahn.Utilities.dll
  - path: '**\*.nupkg'

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 'zGhWvyMSuDz/sqkWbDbKEPKvwnb7+R9RJ7/d2kBUSB3n819QeW6ZiV1ExL9s5uSi'
  on:
    branch: master
    appveyor_repo_tag: true
