version: 2.0.0.{build}

branches:
  only:
    - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/src.csproj --verbosity m

build:
  - cmd: dotnet publish -c Release

artifacts:
  - path: \Utilities\bin\Release\netcoreapp2.2\publish\Emerlahn.Utilities.dll
    name: Emerlahn.Utilities

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 'zGhWvyMSuDz/sqkWbDbKEPKvwnb7+R9RJ7/d2kBUSB3n819QeW6ZiV1ExL9s5uSi'
  on:
    branch: master
    appveyor_repo_tag: true

deploy: off