version: 1.0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore

build:
  project: MarkdownLog.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Utilities\bin\Release\Emerlahn.Utilities.dll
    name: Emerlahn.Utilities.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: 
#  artifact: /.*\.nupkg/
  
